/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dulich;

import java.util.ArrayList;

/**
 *
 * @author Admin
 */
public class QuanlysJF extends javax.swing.JFrame {

    /**
     * Creates new form QuanlysJF
     */
    public QuanlysJF() {
        initComponents();
    }
    ArrayList<Chuyenxenoithanh> noit =new ArrayList();
    ArrayList<Chuyenxengoaithanh> ngt =new ArrayList();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        soxe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sotuyen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sokm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        doanhthu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        noiden = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        songaydidc = new javax.swing.JTextField();
        themxe = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hienthi = new javax.swing.JTextArea();
        dsxenoi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        loaixe = new javax.swing.JTextField();
        dsxengoai = new javax.swing.JButton();
        dsdoanhthu = new javax.swing.JButton();
        doanhthungoaithanh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Masochuyen");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Hoten");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Soxe");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Sokm");

        sotuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotuyenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Sotuyen");

        sokm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokmActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Doanhthu");

        doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doanhthuActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Noiden");

        noiden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noidenActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Songaydidc");

        songaydidc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songaydidcActionPerformed(evt);
            }
        });

        themxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        themxe.setForeground(new java.awt.Color(0, 204, 51));
        themxe.setText("Themxe");
        themxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themxeActionPerformed(evt);
            }
        });

        thoat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        thoat.setForeground(new java.awt.Color(255, 51, 102));
        thoat.setText("Thoat");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        hienthi.setColumns(20);
        hienthi.setRows(5);
        jScrollPane2.setViewportView(hienthi);

        dsxenoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dsxenoi.setForeground(new java.awt.Color(204, 0, 0));
        dsxenoi.setText("DSXENOI");
        dsxenoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsxenoiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Loaixe");

        dsxengoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dsxengoai.setForeground(new java.awt.Color(255, 0, 102));
        dsxengoai.setText("DSXENGOAI");
        dsxengoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsxengoaiActionPerformed(evt);
            }
        });

        dsdoanhthu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dsdoanhthu.setForeground(new java.awt.Color(255, 51, 51));
        dsdoanhthu.setText("DOANHTHUNOITHANH");
        dsdoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsdoanhthuActionPerformed(evt);
            }
        });

        doanhthungoaithanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doanhthungoaithanh.setForeground(new java.awt.Color(0, 51, 255));
        doanhthungoaithanh.setText("DOANHTHUNGOAITHANH");
        doanhthungoaithanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doanhthungoaithanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(themxe)
                        .addGap(52, 52, 52)
                        .addComponent(dsxenoi)
                        .addGap(18, 18, 18)
                        .addComponent(dsxengoai)
                        .addGap(27, 27, 27)
                        .addComponent(dsdoanhthu)
                        .addGap(50, 50, 50)
                        .addComponent(doanhthungoaithanh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(soxe, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sokm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(maso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(songaydidc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(31, 31, 31)
                                        .addComponent(noiden, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(thoat)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(noiden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(soxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(songaydidc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sokm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themxe)
                    .addComponent(dsxenoi)
                    .addComponent(dsxengoai)
                    .addComponent(dsdoanhthu)
                    .addComponent(doanhthungoaithanh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thoat)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sotuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sotuyenActionPerformed

    private void sokmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sokmActionPerformed

    private void doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doanhthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doanhthuActionPerformed

    private void noidenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noidenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noidenActionPerformed

    private void songaydidcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songaydidcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songaydidcActionPerformed

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_thoatActionPerformed

    private void themxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themxeActionPerformed
       ArrayList<Chuyenxenoithanh> noit =new ArrayList();
       ArrayList<Chuyenxengoaithanh> ngt =new ArrayList();
        String maso=this.maso.getText();
        String hoTen=this.hoten.getText();
        int soxe=Integer.parseInt(this.soxe.getText());
        int doanhthu=Integer.parseInt(this.doanhthu.getText());
        int sotuyen=Integer.parseInt(this.sotuyen.getText());
        int sokmdidc=Integer.parseInt(this.sokm.getText());
        String noiden=this.noiden.getText();
        int songaydidc=Integer.parseInt(this.songaydidc.getText());
        String loaixe=this.loaixe.getText();
        if(loaixe.equals("1")){
            //System.out.println("MASOCHUYEN\t\tHOTEN\t\tSOXE\t\tSOTUYEN\t\tSOKMDIDC\t\tDOANHTHU");
            Chuyenxenoithanh xenoi=new Chuyenxenoithanh(sotuyen,  sokmdidc, maso, hoTen,  soxe,  doanhthu);
            this.noit.add(xenoi);
            this.hienthi.append(xenoi.toString()+"\n");
            
        }
        else{
            Chuyenxengoaithanh xengoai=new Chuyenxengoaithanh( noiden,  songaydidc,maso,  hoTen, soxe, doanhthu);
            this.ngt.add(xengoai);
            this.hienthi.append(xengoai.toString()+"\n");
        }

    }//GEN-LAST:event_themxeActionPerformed

    private void dsxenoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsxenoiActionPerformed
        this.hienthi.setText("HOTEN\tMASOCHUYEN\tSOXE\tDOANHTHU\t\tSOTUYEN\tSOKM\n"); 
        for(int i=0;i<noit.size();i++){
           // System.out.println("MASOCHUYEN\t\tHOTEN\t\tSOXE\t\tSOTUYEN\t\tSOKMDIDC\t\tDOANHTHU");
           
            this.hienthi.append(noit.get(i).toString()+"\n");
        }
    }//GEN-LAST:event_dsxenoiActionPerformed

    private void dsxengoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsxengoaiActionPerformed
        this.hienthi.setText("HOTEN\tMASOCHUYEN\tSOXE\tDOANHTHU\tNOIDEN\tSONGAYDIDC\n"); 
        for(int i=0;i<ngt.size();i++){
           // System.out.println("MASOCHUYEN\t\tHOTEN\t\tSOXE\t\tSOTUYEN\t\tSOKMDIDC\t\tDOANHTHU");
           
            this.hienthi.append(ngt.get(i).toString()+"\n");
        }  
    }//GEN-LAST:event_dsxengoaiActionPerformed

    private void dsdoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsdoanhthuActionPerformed
       int a=0;
        for(int i=0;i<noit.size();i++)
            {a=a+noit.get(i).getDoanhthu();}
            this.hienthi.setText("DOANH THU NOI THANH:"+a);
        
    }//GEN-LAST:event_dsdoanhthuActionPerformed

    private void doanhthungoaithanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doanhthungoaithanhActionPerformed
         int a=0;
        for(int i=0;i<ngt.size();i++)
            {a=a+ngt.get(i).getDoanhthu();}
            this.hienthi.setText("DOANH THU NGOAI THANH:"+a);
    }//GEN-LAST:event_doanhthungoaithanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlysJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlysJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlysJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlysJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanlysJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doanhthu;
    private javax.swing.JButton doanhthungoaithanh;
    private javax.swing.JButton dsdoanhthu;
    private javax.swing.JButton dsxengoai;
    private javax.swing.JButton dsxenoi;
    private javax.swing.JTextArea hienthi;
    private javax.swing.JTextField hoten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField loaixe;
    private javax.swing.JTextField maso;
    private javax.swing.JTextField noiden;
    private javax.swing.JTextField sokm;
    private javax.swing.JTextField songaydidc;
    private javax.swing.JTextField sotuyen;
    private javax.swing.JTextField soxe;
    private javax.swing.JButton themxe;
    private javax.swing.JButton thoat;
    // End of variables declaration//GEN-END:variables
}
